-- ============================================
-- 02b_seed_precos_base_dados_compras.sql
-- Base de dados de compras completa: 178 produtos com preços reais
-- Fonte: Base_dados_compras.xlsx (folha normalizada), Continente 2024
-- Substitui/expande 02_seed_precos_referencia.sql — mais completa e limpa.
-- Corre DEPOIS de 01_schema_precos.sql
-- ============================================
-- Todos os preços entram como "CAMTIL (base)" no supermercado Continente (geral).
-- Qualquer utilizador pode editar ou adicionar novos preços/supermercados.
-- Idempotente: apaga os preços "CAMTIL (base)" antigos antes de reinserir.

DO $$
DECLARE
  sm_continente UUID;
BEGIN

-- Garantir supermercado base
INSERT INTO supermercados (nome, cadeia, localidade)
VALUES ('Continente (geral)', 'Continente', NULL)
ON CONFLICT (nome) DO NOTHING;

SELECT id INTO sm_continente FROM supermercados WHERE nome = 'Continente (geral)';

-- Limpar preços base antigos (evita duplicados ao recorrer)
DELETE FROM precos WHERE criado_por = 'CAMTIL (base)' AND supermercado_id = sm_continente;

-- Inserir todos os produtos
INSERT INTO precos (produto, categoria, preco, unidade, supermercado_id, criado_por, notas) VALUES
('Cerveja (1 l)', 'bebidas', 1.19, 'L', sm_continente, 'CAMTIL (base)', '1 l'),
('Vinho Branco (1 l)', 'bebidas', 0.85, 'L', sm_continente, 'CAMTIL (base)', '1 l'),
('Sumo De Laranja (1,5 l)', 'bebidas', 1.39, 'L', sm_continente, 'CAMTIL (base)', '1,5 l'),
('Vodka (700 ml)', 'bebidas', 7.99, 'L', sm_continente, 'CAMTIL (base)', '700 ml'),
('Sumo Concentrado (740 ml)', 'bebidas', 4.99, 'L', sm_continente, 'CAMTIL (base)', '740 ml'),
('Farinheira', 'charcutaria', 1.69, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Grana Padano', 'charcutaria', 3.12, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Morcela Para Assar', 'charcutaria', 2.09, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Queijo Feta', 'charcutaria', 2.09, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Queijo Mozzarella', 'charcutaria', 0.99, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Chouriço Corrente (10 uni)', 'charcutaria', 5.99, 'un', sm_continente, 'CAMTIL (base)', '10 uni'),
('Bacon (Cubos) (150 g)', 'charcutaria', 1.65, 'un', sm_continente, 'CAMTIL (base)', '150 g'),
('Bacon (Fatias) (200 g)', 'charcutaria', 1.77, 'un', sm_continente, 'CAMTIL (base)', '200 g'),
('Fiambre Fatiado (200 g)', 'charcutaria', 1.59, 'un', sm_continente, 'CAMTIL (base)', '200 g'),
('Linguiça (200 g)', 'charcutaria', 1.49, 'un', sm_continente, 'CAMTIL (base)', '200 g'),
('Queijo Ralado Para Gratinar (200 g)', 'charcutaria', 1.49, 'un', sm_continente, 'CAMTIL (base)', '200 g'),
('Presunto (250 g)', 'charcutaria', 3.79, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Batatas Fritas Para Fritar (1 kg)', 'congelados', 1.99, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Brócolos Congelados (1 kg)', 'congelados', 1.88, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Ervilhas Congeladas (1 kg)', 'congelados', 1.38, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Gelado De Nata (1 l)', 'congelados', 2.39, 'L', sm_continente, 'CAMTIL (base)', '1 l'),
('Geladinhos (12 uni)', 'congelados', 3.09, 'un', sm_continente, 'CAMTIL (base)', '12 uni'),
('Delícias Do Mar Congeladas (250 g)', 'congelados', 1.21, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Miolo Camarão (250 g)', 'congelados', 3.49, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Espargos Congelados (300 g)', 'congelados', 3.19, 'un', sm_continente, 'CAMTIL (base)', '300 g'),
('Crepes Chineses (4 uni)', 'congelados', 2.19, 'un', sm_continente, 'CAMTIL (base)', '4 uni'),
('Mistura Pimentos Congelados (400 g)', 'congelados', 1.39, 'un', sm_continente, 'CAMTIL (base)', '400 g'),
('Preparado Marisco Congelado (400 g)', 'congelados', 3.76, 'un', sm_continente, 'CAMTIL (base)', '400 g'),
('Couve Flor Congelada (750 g)', 'congelados', 1.38, 'un', sm_continente, 'CAMTIL (base)', '750 g'),
('Alho Francês Congelado (750 gr)', 'congelados', 0.98, 'un', sm_continente, 'CAMTIL (base)', '750 gr'),
('Paloco Desfiado Congelado (900 g)', 'congelados', 6.49, 'un', sm_continente, 'CAMTIL (base)', '900 g'),
('Azeitonas Frasco (210g)', 'enlatados', 1.09, 'un', sm_continente, 'CAMTIL (base)', '210g'),
('Tomate Triturado (390 g)', 'enlatados', 0.69, 'un', sm_continente, 'CAMTIL (base)', '390 g'),
('Leite De Côco (400 ml)', 'enlatados', 1.39, 'L', sm_continente, 'CAMTIL (base)', '400 ml'),
('Cogumelos Laminados (780g)', 'enlatados', 1.19, 'un', sm_continente, 'CAMTIL (base)', '780g'),
('Ervilhas (830 g)', 'enlatados', 1.39, 'un', sm_continente, 'CAMTIL (base)', '830 g'),
('Feijão Encarnado Cozido (830 g)', 'enlatados', 1.19, 'un', sm_continente, 'CAMTIL (base)', '830 g'),
('Feijão Frade Cozido (830 g)', 'enlatados', 1.19, 'un', sm_continente, 'CAMTIL (base)', '830 g'),
('Feijão Preto Cozido (830 g)', 'enlatados', 1.19, 'un', sm_continente, 'CAMTIL (base)', '830 g'),
('Grão De Bico (830 g)', 'enlatados', 1.19, 'un', sm_continente, 'CAMTIL (base)', '830 g'),
('Polpa De Manga (860 g)', 'enlatados', 3.29, 'un', sm_continente, 'CAMTIL (base)', '860 g'),
('Leite Condensado (97 g)', 'enlatados', 1.45, 'un', sm_continente, 'CAMTIL (base)', '97 g'),
('Ananás (825 g)', 'enlatados', 2.19, 'un', sm_continente, 'CAMTIL (base)', '825 g'),
('Atum Ao Natural (270 g)', 'enlatados', 2.69, 'un', sm_continente, 'CAMTIL (base)', '270 g'),
('Beterraba (560 g)', 'enlatados', 0.99, 'un', sm_continente, 'CAMTIL (base)', '560 g'),
('Edamame (150 g)', 'enlatados', 1.59, 'un', sm_continente, 'CAMTIL (base)', '150 g'),
('Milho (300 g)', 'enlatados', 1.15, 'un', sm_continente, 'CAMTIL (base)', '300 g'),
('Salsichas (380 g)', 'enlatados', 1.19, 'un', sm_continente, 'CAMTIL (base)', '380 g'),
('Tomate Pelado (780 g)', 'enlatados', 1.29, 'un', sm_continente, 'CAMTIL (base)', '780 g'),
('Alho Francês (1 kg)', 'frutas_legumes', 2.82, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Cenouras (1 kg)', 'frutas_legumes', 1.19, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Courgettes (1 kg)', 'frutas_legumes', 1.79, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Couve Caldo Verde (1 kg)', 'frutas_legumes', 4.36, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Maçã (1 kg)', 'frutas_legumes', 1.59, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Pepino (1 kg)', 'frutas_legumes', 1.69, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Pimento (1 kg)', 'frutas_legumes', 3.99, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Tomate (1 kg)', 'frutas_legumes', 1.99, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Abóbora Manteiga', 'frutas_legumes', 1.60, 'un', sm_continente, 'CAMTIL (base)', '1 un'),
('Alface', 'frutas_legumes', 0.59, 'un', sm_continente, 'CAMTIL (base)', '1 un'),
('Cebola Roxa', 'frutas_legumes', 0.29, 'un', sm_continente, 'CAMTIL (base)', '1 un'),
('Couve Coração', 'frutas_legumes', 1.16, 'un', sm_continente, 'CAMTIL (base)', '1 un'),
('Limão', 'frutas_legumes', 0.36, 'un', sm_continente, 'CAMTIL (base)', '1 un'),
('Melancia', 'frutas_legumes', 4.45, 'un', sm_continente, 'CAMTIL (base)', '1 un'),
('Melão', 'frutas_legumes', 5.00, 'un', sm_continente, 'CAMTIL (base)', '1 un'),
('Cebola (2 kg)', 'frutas_legumes', 3.34, 'kg', sm_continente, 'CAMTIL (base)', '2 kg'),
('Coentros (50 g)', 'frutas_legumes', 0.99, 'un', sm_continente, 'CAMTIL (base)', '50 g'),
('Salsa (50 g)', 'frutas_legumes', 0.99, 'un', sm_continente, 'CAMTIL (base)', '50 g'),
('Alho (7 uni)', 'frutas_legumes', 1.99, 'un', sm_continente, 'CAMTIL (base)', '7 uni'),
('Espinafres Em Folha (170 g)', 'frutas_legumes', 0.99, 'un', sm_continente, 'CAMTIL (base)', '170 g'),
('Leite (1 l)', 'lacticinios', 0.78, 'L', sm_continente, 'CAMTIL (base)', '1 l'),
('Natas Culinária (200 ml)', 'lacticinios', 0.42, 'L', sm_continente, 'CAMTIL (base)', '200 ml'),
('Natas Para Bater (200 ml)', 'lacticinios', 0.75, 'L', sm_continente, 'CAMTIL (base)', '200 ml'),
('Manteiga (250 g)', 'lacticinios', 1.87, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Molho Bechamel (500 ml)', 'lacticinios', 1.59, 'L', sm_continente, 'CAMTIL (base)', '500 ml'),
('Iogurtes Naturais (8 uni)', 'lacticinios', 1.48, 'un', sm_continente, 'CAMTIL (base)', '8 uni'),
('Detergente Loiça (1 l)', 'limpeza', 0.99, 'L', sm_continente, 'CAMTIL (base)', '1 l'),
('Esfregões De Aço (4 uni)', 'limpeza', 0.89, 'un', sm_continente, 'CAMTIL (base)', '4 uni'),
('Papel Aderente', 'limpeza', 1.29, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Papel Prata', 'limpeza', 2.49, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Spray Limpa Tudo', 'limpeza', 2.29, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Papel Cozinha (2 uni)', 'limpeza', 1.19, 'un', sm_continente, 'CAMTIL (base)', '2 uni'),
('Esfregões (3 uni)', 'limpeza', 0.45, 'un', sm_continente, 'CAMTIL (base)', '3 uni'),
('Sacos Do Lixo 50L (3x15 uni)', 'limpeza', 3.79, 'un', sm_continente, 'CAMTIL (base)', '3x15 uni'),
('Saquinhos Plástico Congelar 3l (50 uni)', 'limpeza', 1.19, 'un', sm_continente, 'CAMTIL (base)', '50 uni'),
('Desinfetante Mãos (500 ml)', 'limpeza', 2.89, 'L', sm_continente, 'CAMTIL (base)', '500 ml'),
('Panos Amarelos Continente Limpeza (6 uni)', 'limpeza', 1.09, 'un', sm_continente, 'CAMTIL (base)', '6 uni'),
('Papel Higienico (60 uni)', 'limpeza', 11.15, 'un', sm_continente, 'CAMTIL (base)', '60 uni'),
('Fósforos (4 uni)', 'limpeza', 0.69, 'un', sm_continente, 'CAMTIL (base)', '4 uni'),
('Lixívia (5 l)', 'limpeza', 1.99, 'L', sm_continente, 'CAMTIL (base)', '5 l'),
('Luvas De Borracha', 'limpeza', 0.69, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Toalhitas Cozinha (80 uni)', 'limpeza', 1.69, 'un', sm_continente, 'CAMTIL (base)', '80 uni'),
('Açúcar (1 kg)', 'mercearia', 1.39, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Arroz Vaporizado (1 kg)', 'mercearia', 1.23, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Cereais Chocapic (1 kg)', 'mercearia', 2.99, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Corn Flakes (1 kg)', 'mercearia', 3.29, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Esparguete (1 kg)', 'mercearia', 1.21, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Farinha (1 kg)', 'mercearia', 0.62, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Gaspacho (1 l)', 'mercearia', 1.69, 'L', sm_continente, 'CAMTIL (base)', '1 l'),
('Ovos', 'mercearia', 0.20, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Pão', 'mercearia', 0.14, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Sopa Canja (Pacotes Em Pó)', 'mercearia', 0.99, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Sopa Cogumelos (Pacotes Em Pó)', 'mercearia', 0.89, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Sopa De Cebola (Pacotes Em Pó)', 'mercearia', 0.89, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Sopa De Marisco (Pacotes Em Pó)', 'mercearia', 0.89, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Sopa Espargos (Pacotes Em Pó)', 'mercearia', 0.99, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Sopa Legumes (Pacotes Em Pó)', 'mercearia', 0.99, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Sopa Rabo De Boi (Pacotes Em Pó)', 'mercearia', 0.89, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Sopa Tomate (Pacotes Em Pó)', 'mercearia', 1.34, 'un', sm_continente, 'CAMTIL (base)', '1 uni'),
('Chocolate Tablete (100 g)', 'mercearia', 0.69, 'un', sm_continente, 'CAMTIL (base)', '100 g'),
('Tabletes Chocolate Leite (100 g)', 'mercearia', 0.99, 'un', sm_continente, 'CAMTIL (base)', '100 g'),
('Tabletes Chocolate Negro (100 g)', 'mercearia', 1.19, 'un', sm_continente, 'CAMTIL (base)', '100 g'),
('Chocolate Em Pó (125 g)', 'mercearia', 0.89, 'un', sm_continente, 'CAMTIL (base)', '125 g'),
('Filipinos (128 g)', 'mercearia', 0.75, 'un', sm_continente, 'CAMTIL (base)', '128 g'),
('Bolachas Oreo Marca Continente (154 g)', 'mercearia', 0.99, 'un', sm_continente, 'CAMTIL (base)', '154 g'),
('Arroz Carolino (1kg)', 'mercearia', 1.25, 'kg', sm_continente, 'CAMTIL (base)', '1kg'),
('Arroz Risotto (1kg)', 'mercearia', 2.10, 'kg', sm_continente, 'CAMTIL (base)', '1kg'),
('Chá (25 uni)', 'mercearia', 0.79, 'un', sm_continente, 'CAMTIL (base)', '25 uni'),
('Batatas Fritas Onduladas (250 g)', 'mercearia', 1.25, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Café Moagem Grossa/Fina (250 g)', 'mercearia', 1.79, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Couscous (250 g)', 'mercearia', 0.59, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Massa Para Canja (250 g)', 'mercearia', 0.55, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Milho Pipocas (250 g)', 'mercearia', 0.39, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Rebuçados (250 g)', 'mercearia', 2.49, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Chalotas (250 g)', 'mercearia', 1.09, 'un', sm_continente, 'CAMTIL (base)', '250 g'),
('Gomas Ursinhos (300 g)', 'mercearia', 1.49, 'un', sm_continente, 'CAMTIL (base)', '300 g'),
('Pão Ralado (300 g)', 'mercearia', 0.60, 'un', sm_continente, 'CAMTIL (base)', '300 g'),
('Nutella Cigana (350 g)', 'mercearia', 2.45, 'un', sm_continente, 'CAMTIL (base)', '350 g'),
('Pão Bimbo (375 g)', 'mercearia', 1.78, 'un', sm_continente, 'CAMTIL (base)', '375 g'),
('Batata Palha (400 g)', 'mercearia', 1.99, 'un', sm_continente, 'CAMTIL (base)', '400 g'),
('Farinha Maizena (400 g)', 'mercearia', 2.60, 'un', sm_continente, 'CAMTIL (base)', '400 g'),
('Palmiers (400 g)', 'mercearia', 4.00, 'un', sm_continente, 'CAMTIL (base)', '400 g'),
('Soja Fina (400 g)', 'mercearia', 1.89, 'un', sm_continente, 'CAMTIL (base)', '400 g'),
('Macarrão Grande (500 g)', 'mercearia', 0.89, 'un', sm_continente, 'CAMTIL (base)', '500 g'),
('Massa Espiral (500 g)', 'mercearia', 0.79, 'un', sm_continente, 'CAMTIL (base)', '500 g'),
('Massa Lasanha (500 g)', 'mercearia', 1.59, 'un', sm_continente, 'CAMTIL (base)', '500 g'),
('Massa Penne (500 g)', 'mercearia', 0.98, 'un', sm_continente, 'CAMTIL (base)', '500 g'),
('Puré De Batata (500 g)', 'mercearia', 2.29, 'un', sm_continente, 'CAMTIL (base)', '500 g'),
('Biscoitos Canela (750 g)', 'mercearia', 3.49, 'un', sm_continente, 'CAMTIL (base)', '750 g'),
('Bolachas Maria (800 g)', 'mercearia', 1.89, 'un', sm_continente, 'CAMTIL (base)', '800 g'),
('Bolachas Tostadas (800 g)', 'mercearia', 1.79, 'un', sm_continente, 'CAMTIL (base)', '800 g'),
('Chocolate Nesquik (800 g)', 'mercearia', 3.49, 'un', sm_continente, 'CAMTIL (base)', '800 g'),
('Marmelada (900 g)', 'mercearia', 2.69, 'un', sm_continente, 'CAMTIL (base)', '900 g'),
('Polpa De Tomate (1 kg)', 'temperos', 1.99, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Molho De Soja (200 ml)', 'temperos', 0.99, 'L', sm_continente, 'CAMTIL (base)', '200 ml'),
('Molho Inglês (200 ml)', 'temperos', 0.99, 'L', sm_continente, 'CAMTIL (base)', '200 ml'),
('Molho Piri-Piri (200 ml)', 'temperos', 0.55, 'L', sm_continente, 'CAMTIL (base)', '200 ml'),
('Molho Sriracha (200 ml)', 'temperos', 1.49, 'L', sm_continente, 'CAMTIL (base)', '200 ml'),
('Maionese (470g)', 'temperos', 1.59, 'un', sm_continente, 'CAMTIL (base)', '470g'),
('Molho De Francesinha (500gr)', 'temperos', 1.99, 'un', sm_continente, 'CAMTIL (base)', '500gr'),
('Ketchup (560g)', 'temperos', 1.29, 'un', sm_continente, 'CAMTIL (base)', '560g'),
('Bifanas', 'talho', 6.59, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Bife De Vaca', 'talho', 12.25, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Bifes De Peru', 'talho', 7.99, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Carne De Porco (Rojões)', 'talho', 5.08, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Carne Porco Picada', 'talho', 7.98, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Carne Vaca Picada', 'talho', 9.43, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Entrecosto Porco', 'talho', 5.99, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Fiambre (Para Cubos)', 'talho', 7.73, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Frango Inteiro', 'talho', 2.34, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Peito De Frango', 'talho', 6.59, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Queijo Flamengo Em Barra', 'talho', 7.99, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Salsicha Fresca', 'talho', 5.98, 'kg', sm_continente, 'CAMTIL (base)', 'Preço por kg'),
('Sal Grosso (1 kg)', 'temperos', 0.25, 'kg', sm_continente, 'CAMTIL (base)', '1 kg'),
('Óleo (1 l)', 'temperos', 1.45, 'L', sm_continente, 'CAMTIL (base)', '1 l'),
('Vinagre (1 l)', 'temperos', 0.75, 'L', sm_continente, 'CAMTIL (base)', '1 l'),
('Louro (10 g)', 'temperos', 0.69, 'un', sm_continente, 'CAMTIL (base)', '10 g'),
('Orégãos (10 g)', 'temperos', 0.49, 'un', sm_continente, 'CAMTIL (base)', '10 g'),
('Caldo Knorr Galinha (12 uni)', 'temperos', 0.99, 'un', sm_continente, 'CAMTIL (base)', '12 uni'),
('Caldos Knorr Legumes (12 uni)', 'temperos', 0.99, 'un', sm_continente, 'CAMTIL (base)', '12 uni'),
('Caldos Knorr Carne (24 uni)', 'temperos', 1.29, 'un', sm_continente, 'CAMTIL (base)', '24 uni'),
('Azeite (3 l)', 'temperos', 17.69, 'L', sm_continente, 'CAMTIL (base)', '3 l'),
('Açafrão (45 g)', 'temperos', 0.59, 'un', sm_continente, 'CAMTIL (base)', '45 g'),
('Alho Em Pó (45 g)', 'temperos', 0.89, 'un', sm_continente, 'CAMTIL (base)', '45 g'),
('Caril (45 g)', 'temperos', 0.69, 'un', sm_continente, 'CAMTIL (base)', '45 g'),
('Pimenta (50 g)', 'temperos', 0.79, 'un', sm_continente, 'CAMTIL (base)', '50 g'),
('Vinagre Balsamico (500 ml)', 'temperos', 1.99, 'L', sm_continente, 'CAMTIL (base)', '500 ml'),
('Pesto (190 g)', 'temperos', 1.69, 'un', sm_continente, 'CAMTIL (base)', '190 g'),
('Sumo Limão Concentrado (200 ml)', 'temperos', 0.59, 'L', sm_continente, 'CAMTIL (base)', '200 ml');

END $$;
